---

###############################################################################
# Valid defaults
###############################################################################

# OpenNebula repository version
opennebula_repository_version: '6.9'

# Repository of the OpenNebula packages
opennebula_repository_base: 'https://downloads.opennebula.io/repo/{{ opennebula_repository_version }}'
