---
- name: Create oneadmin keys
  vars:
    _profiles_with_pools: >-
      {{ ceph_opennebula_mon_pools | map(attribute='name')
                                   | map('regex_replace', '^', 'profile rbd pool=')
                                   | join(',') }}

  command: ceph auth get-or-create client.oneadmin mon 'profile rbd' osd '{{ _profiles_with_pools }}'
  changed_when: false

- name: get oneadmin key
  shell: ceph auth get-key client.oneadmin
  register: ceph_oneadmin_key

- name: get oneadmin keyring
  shell: ceph auth export client.oneadmin
  register: ceph_oneadmin_keyring
