---
- name: Install OpenNebula node package
  apt:
    name: opennebula-node
    state: latest
  register: apt_result
  until: apt_result is success
  retries: 3
  delay: 10

- include_tasks: kvm.yml
  when: opennebula_node_kvm_manage_kvm == True

- include_tasks: libvirt.yml
- include_tasks: security.yml

- name: "create datastore for ONE_LOCATION"
  file: path={{ one_location }}/var/datastores owner=oneadmin group=oneadmin state=directory
  when: one_location is defined
