---

- name: Create /var/lib/one/.ssh directory
  file:
    path: /var/lib/one/.ssh
    owner: 9869
    group: 9869
    mode: 0700
    state: directory

- include_tasks: sshd.yml
  when: opennebula_ssh_manage_sshd == True

- include_tasks: deploy_local.yml
  when: opennebula_ssh_deploy_local == True

- include_tasks: root_authkeys.yml
  when: opennebula_ssh_keys_import_root_keys == True
